package helio.tests.projects;

import java.io.IOException;

import org.apache.jena.rdf.model.Model;
import org.junit.Assert;
import org.junit.Test;

import helio.blueprints.exceptions.ExtensionNotFoundException;
import helio.blueprints.exceptions.IncompatibleMappingException;
import helio.blueprints.exceptions.IncorrectMappingException;
import helio.tests.TestUtils;

public class BimerTest {

	@Test
	public void test1()  {

		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-1-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-1-mapping.json"));

		Assert.assertTrue(TestUtils.compareModels(generated, expected));
	}



	/**
	 * In this test the subject uses the function now() therefore there is no way to check if the subjects are the same in the expected rdf and the generated rdf.
	 * This test only verifies the predicate and objects from the expected and generated RDF.
	 * @throws IOException
	 * @throws InterruptedException
	 * @throws SparqlQuerySyntaxException
	 * @throws SparqlRemoteEndpointException
	 * @throws ExtensionNotFoundException 
	 * @throws IncorrectMappingException 
	 * @throws MappingExecutionException 
	 * @throws IncompatibleMappingException 
	 */
	@Test
	public void test2()  {
		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-1-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-2-mapping.json"));

		boolean equivalent = expected.listStatements().toList()
						.parallelStream()
						.map(st -> generated.contains(null, st.getPredicate(), st.getObject()))
						.allMatch( elem -> elem);
		Assert.assertTrue(equivalent);

	}


	@Test
	public void test3()  {
		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-3-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-3-mapping.json"));



		Assert.assertTrue(TestUtils.compareModels(generated, expected));
	}

	/**
	 * In this test multiple datatype literals are generated by the same object template. Also two subjects are generated by the same subject template
	 * @throws IOException
	 * @throws InterruptedException
	 * @throws SparqlQuerySyntaxException
	 * @throws SparqlRemoteEndpointException
	 * @throws ExtensionNotFoundException 
	 * @throws IncorrectMappingException 
	 * @throws MappingExecutionException 
	 * @throws IncompatibleMappingException 
	 */
	@Test
	public void test4()  {
		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-4-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-4-mapping.json"));

		Assert.assertTrue(TestUtils.compareModels(generated, expected));
	}

	/**
	  * In this test multiple literals are generated by the same object template. Also two subjects are generated by the same subject template
	 * @throws IOException
	 * @throws InterruptedException
	 * @throws SparqlQuerySyntaxException
	 * @throws SparqlRemoteEndpointException
	 * @throws ExtensionNotFoundException 
	 * @throws IncorrectMappingException 
	 * @throws MappingExecutionException 
	 * @throws IncompatibleMappingException 
	 */
	@Test
	public void test5(){
		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-5-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-5-mapping.json"));

		Assert.assertTrue(TestUtils.compareModels(generated, expected));
	}


	/**
	  * In this test multiple lang literals are generated by the same object template. Also two subjects are generated by the same subject template
	 * @throws IOException
	 * @throws InterruptedException
	 * @throws SparqlQuerySyntaxException
	 * @throws SparqlRemoteEndpointException
	 * @throws ExtensionNotFoundException 
	 * @throws IncorrectMappingException 
	 * @throws MappingExecutionException 
	 * @throws IncompatibleMappingException 
	 */
	@Test
	public void test6()  {
		Model expected = TestUtils.readModel("./src/test/resources/bimr-tests/helio-6-expected.ttl");
		Model generated = TestUtils.generateRDFSynchronously(TestUtils.processJMapping("./src/test/resources/bimr-tests/helio-6-mapping.json"));


		Assert.assertTrue(TestUtils.compareModels(generated, expected));
	}


}
